%% Creating Cell Arrays for all computed Variables of the Financial Model

% Creating Year Variable

Year=0:ProjectLife;

%% Cell Array for Input Sheet Variables

% Deciding Depreciation Type

if (SL==1)
    
    DepreciationType='SL';
    
elseif (AD==1)
    
    DepreciationType='AD';    
    
end

InputsSheet_TableArray=cell(41,4);

% Filling Static and Dynamic Data

InputsSheet_TableArray={'Sheet:Inputs','','','';...
    'Capacity','','','';...
    'Plant Capacity','',PlantCapacity,'MW';...
    'Capital Cost','','','';...
    'Unit EPC Cost','Rs.',UnitEPCCost,'Cr/MW';...
    'Land Cost','Rs.',LandCost,'Lacs per Acre';...
    'Land Requirement','',LandRequirement,'Acres/MW';...
    'Unit Land Cost','Rs.',UnitLandCost,'Cr/MW';...
    'Unit Other Cost','Rs.',UnitOtherCosts,'Cr/MW';...
    'Unit Development Cost','Rs.',UnitDevelopmentCost,'Cr/MW';...
    'Total Projectt Cost','Rs.',TotalProjectCost,'Cr/MW';...
    'Operation & Maintenance','','','';...
    'O&M Cost','%',OM_Cost_Percent,'of Project Cost';...
    'Escalation in O&M Cost','%',OM_Escalation_Percent,'Annually';...
    'Performance Parameters','','','';...
    'CUF','%',CUF_Percent,'';...
    'Annual Performance Deration','%',AnnualPerformance_Percent,'per Year';...
    'Auxiliary Consumption','%',AuxConsp_Percent,'of Gross Generation';...
    'Project Life','',ProjectLife,'Years';...
    'Tariff','','','';...
    'Feed-In Tariff','Rs.',FeedInTariff,'per kWh';...
    'Financial Parameters','','','';...
    'Debt Fraction','%',DebtFraction_Percent,'of the Capital Cost';...
    'Loan Tenure','',LoanTenure,'Years';...
    'Moratorium Period','',MoratoriumPeriod,'Years';...
    'Interest Rate of Loan','%',Int_Loan_ROI_Percent,'p.a.';...
    'Insurance Cost','%',InsuranceCost_Percent,'of Capital Cost';...
    'Working Capital','sum of',OM_NumMonths,'Months O&M Expense';...
    '','and',EnergyCharges_NumMonths,'Months Energy Charges';...
    '','and',OM_Spares_Percent,'% of O&M Expenses as Spares';...
    'Interest on Working Capital','%',WC_Int_Percent,'p.a.';...
    'Rate of S.l. Depreciation','%',FirstYearSegment_ROI_Percent,'for the first';...
    '','',FirstYearSegment,'Years';...
    '','and',NextYearSegment_ROI_Percent,'For the Next';...
    '','',NextYearSegment,'Years';...
    'Rate of Accelerated Depreciation','%',AD_ROI_Percent,'p.a.';...
    'Corporae Tax','',CorporateTax_ROI_Percent,'Corporate Tax Rate';...
    'Minimum Alternate Tax','',MinAlternateTax_ROI_Percent,'';...
    '','for',AD_Years,'Years';...
    'Discount Factor for Calculation','%',DiscountForCalculation_Percent,'p.a.';...
    'Depreciation','',DepreciationType,''};
    

%% Cell Array for Revenue Sheet Variables

RevenueSheet_TableArray=cell(9,(2+(ProjectLife+1)));

% Filling Static Data

RevenueSheet_TableArray(:,1:2)={'Sheet:Revenue','';...
    'Year','';...
    'Energy Generation','MU';...
    'Auxiliary Consumption','MU';...
    'Net Energy Generation','MU';...
    'Revenue','';...
    'From Sale of Power','Rs. Cr.';...
    'Net From Sale','Rs. Cr.';...
    'Net Revenue','Rs. Cr.'};
    
 % Filling Dynamic (Computed) Data   
 
 for i=1:(ProjectLife+1)
 
    RevenueSheet_TableArray(2,(i+2))={Year(1,i)};
    
    RevenueSheet_TableArray(3,(i+2))={Eg(1,i)};

    RevenueSheet_TableArray(4,(i+2))={AuxConsp(1,i)};

    RevenueSheet_TableArray(5,(i+2))={NetEg(1,i)};

    RevenueSheet_TableArray(7,(i+2))={Rev_SalePower(1,i)};

    RevenueSheet_TableArray(8,(i+2))={Rev_NetSalePower(1,i)};

    RevenueSheet_TableArray(9,(i+2))={Rev_Net(1,i)};
    
 end

%% Cell Array for Debt Servicing Sheet Variables

DebtServicingSheet_TableArray=cell(16,(2+(ProjectLife+1)));

% Filling Static Data

DebtServicingSheet_TableArray(:,1:2)={'Sheet:Debt Servicing','';...
    'Year','';...
    'Debt Servicing (Without VGF)','';...
    'Opening Balance','Rs. Cr.';...
    'Annual Principal Amount','Rs. Cr.';...
    'Closing Balance','Rs. Cr.';...
    'Interest','';...
    'Interest','Rs. Cr.';...
    'Repayment Debt+Interest','Rs. Cr.';...    
    'Debt Servicing (With VGF)','';...
    'Opening Balance','Rs. Cr.';...
    'Annual Principal Amount','Rs. Cr.';...
    'Closing Balance','Rs. Cr.';...
    'Interest','';...
    'Interest','Rs. Cr.';...
    'Repayment Debt+Interest','Rs. Cr.'};

% Filling Dynamic (Computed) Data  
 
 for i=1:(ProjectLife+1)
     
    DebtServicingSheet_TableArray(2,(i+2))={Year(1,i)};
 
    DebtServicingSheet_TableArray(4,(i+2))={OpenBalance(1,i)};

    DebtServicingSheet_TableArray(5,(i+2))={AnPrinAmt(1,i)};

    DebtServicingSheet_TableArray(6,(i+2))={CloseBal(1,i)};

    DebtServicingSheet_TableArray(8,(i+2))={Int_Without_VGF(1,i)};

    DebtServicingSheet_TableArray(9,(i+2))={Repayment_Without_VGF(1,i)};

    DebtServicingSheet_TableArray(11,(i+2))={OpenBalance(1,i)};

    DebtServicingSheet_TableArray(12,(i+2))={AnPrinAmt(1,i)};

    DebtServicingSheet_TableArray(13,(i+2))={CloseBal(1,i)};

    DebtServicingSheet_TableArray(15,(i+2))={Int_With_VGF(1,i)};

    DebtServicingSheet_TableArray(16,(i+2))={Repayment_With_VGF(1,i)};
    
 end 

%% Cell Array for Depreciation Sheet Variables

DepreciationSheet_TableArray=cell(12,(2+(ProjectLife+1)));

% Filling Static Data

DepreciationSheet_TableArray(:,1:2)={'Sheet:Depreciation','';...
    'Year','';...
    'Straight Line Depreciation','';...
    'Opening Amount','Rs. Cr.';...
    'Depreciation in %','%';...
    'Depreciation Amount','Rs. Cr.';...
    'Closing Balance','Rs. Cr.';...
    'Acceleraed Depreciation','';...
    'Accelerated Depreciation','Rs. Cr.';...
    'Depreciation in %','%';...
    'Depreciation Amount','Rs. Cr.';...
    'Closing Balance','Rs. Cr.'};

% Filling Dynamic (Computed) Data 

for i=1:(ProjectLife+1)
     
    DepreciationSheet_TableArray(2,(i+2))={Year(1,i)};
 
    DepreciationSheet_TableArray(4,(i+2))={SL_OpenAmt(1,i)};

    DepreciationSheet_TableArray(5,(i+2))={SL_DepRate(1,i)};

    DepreciationSheet_TableArray(6,(i+2))={SL_DepAmt(1,i)};
    
    DepreciationSheet_TableArray(7,(i+2))={SL_CloseBal(1,i)};
    
    DepreciationSheet_TableArray(9,(i+2))={AD_Amt(1,i)};

    DepreciationSheet_TableArray(10,(i+2))={AD_DepRate(1,i)};

    DepreciationSheet_TableArray(11,(i+2))={AD_DepAmt(1,i)};
    
    DepreciationSheet_TableArray(12,(i+2))={AD_CloseBal(1,i)};    
   
 end 

%% Cell Array for Operational Expenditure Sheet Variables

OperationalExpenditureSheet_TableArray=cell(6,(2+(ProjectLife+1)));

% Filling Static Data

OperationalExpenditureSheet_TableArray(:,1:2)={'Sheet:Operational Expenditure','';...
    'Year','';...
    'Operational Expenses','';...
    'O&M Cost','Rs. Cr.';...
    'Insurance Cost','Rs. Cr.';...
    'Net Operational Expenses','Rs. Cr.'};

% Filling Dynamic (Computed) Data 

for i=1:(ProjectLife+1)
     
    OperationalExpenditureSheet_TableArray(2,(i+2))={Year(1,i)};
    
    OperationalExpenditureSheet_TableArray(4,(i+2))={OpEx_Cost(1,i)};
 
    OperationalExpenditureSheet_TableArray(5,(i+2))={OpEx_Insurance(1,i)};

    OperationalExpenditureSheet_TableArray(6,(i+2))={OpEx_NetExpense(1,i)}; 
   
 end 

%% Cell Array for Working Capital Sheet Variables

WorkingCapitalSheet_TableArray=cell(9,(2+(ProjectLife+1)));

% Filling Static Data

WorkingCapitalSheet_TableArray(:,1:2)={'Sheet:WorkingCapital','';...
    'Year','';...
    'Working Capital','';...
    'From O&M Expenses','Rs. Cr.';...
    'From Energy Charges','Rs. Cr.';...
    'From Spares','Rs. Cr.';...
    'Totsl Working Capital','Rs. Cr.';...
    'Interest on Working Capital','';...
    'Interest on Working Capital','Rs. Cr.'};

% Filling Dynamic (Computed) Data 

for i=1:(ProjectLife+1)
     
    WorkingCapitalSheet_TableArray(2,(i+2))={Year(1,i)};
    
    WorkingCapitalSheet_TableArray(4,(i+2))={WC_OM(1,i)};
 
    WorkingCapitalSheet_TableArray(5,(i+2))={WC_Energy(1,i)};

    WorkingCapitalSheet_TableArray(6,(i+2))={WC_Spares(1,i)}; 
    
    WorkingCapitalSheet_TableArray(7,(i+2))={WC_Total(1,i)};

    WorkingCapitalSheet_TableArray(9,(i+2))={WC_Int(1,i)};    
   
 end 

%% Cell Array for Cash Flow Sheet Variables

CashFlowSheet_TableArray=cell(40,(2+(ProjectLife+1)));

% Filling Static Data

CashFlowSheet_TableArray(:,1:2)={'Sheet:Cash Flow','';...
'Year','';...
'Revenue','';...
'Revenue from Sale','Rs. Cr.';...
'Operational Expenditure','';...
'Net Operational Expenditure','Rs. Cr.';...
'EBITDA','Rs. Cr.';...
'Depreciation (Straight Line)','';...
'Depreciation','Rs. Cr.';...
'EBIT','Rs. Cr.';...
'Interest','';...
'Interest on Debt','Rs. Cr.';...
'Interest on Working Capital','Rs. Cr.';...
'EBT','Rs. Cr.';...
'Tax','';...
'Applicable Tax','%';...
'Tax Amount','Rs. Cr.';...
'PAT','Rs. Cr.';...
'Project Cash Flow','';...
'Project Cost','Rs. Cr.';...
'Revenue From Sale','Rs. Cr.';...
'Net Operational Expenditure','Rs. Cr.';...
'Net Cash Flow','Rs. Cr.';...
'Project IRR','%';...
'Project NPV','Rs. Cr.';...
'Equity Cash Flow','';...
'Equity Invested','Rs. Cr.';...
'Revenue from Sale','Rs. Cr.';...
'Net Operational Expenditure','Rs. Cr.';...
'Net Interest','Rs. Cr.';...
'Tax','Rs. Cr.';...
'Principal Payments','Rs. Cr.';...
'Cash Flow after Principal','Rs. Cr.';...
'Equity IRR','%';...
'Equity NPV','Rs. Cr.';...
'Debt Service Coverage Ratio','';...
'Net Operating Income','Rs. Cr.';...
'Debt Service','Rs. Cr.';...
'Debt Service Coverage Ratio','';...
'Average DSCR',''};

% Filling Dynamic (Computed) Data 

for i=1:(ProjectLife+1)
     
    CashFlowSheet_TableArray(2,(i+2))={Year(1,i)};
    
    CashFlowSheet_TableArray(4,(i+2))={CF_RevSaleNet(1,i)};
 
    CashFlowSheet_TableArray(6,(i+2))={CF_OpEx(1,i)};

    CashFlowSheet_TableArray(7,(i+2))={EBITDA(1,i)}; 
    
    CashFlowSheet_TableArray(9,(i+2))={CF_DepAmt(1,i)};
    
    CashFlowSheet_TableArray(10,(i+2))={EBIT(1,i)};   
    
    CashFlowSheet_TableArray(12,(i+2))={CF_IntAmt(1,i)};

    CashFlowSheet_TableArray(13,(i+2))={WC_Int(1,i)};
    
    CashFlowSheet_TableArray(14,(i+2))={EBT(1,i)};
 
    CashFlowSheet_TableArray(16,(i+2))={CF_AppTax(1,i)};

    CashFlowSheet_TableArray(17,(i+2))={CF_TaxAmt(1,i)}; 
    
    CashFlowSheet_TableArray(18,(i+2))={PAT(1,i)};

    CashFlowSheet_TableArray(20,(i+2))={CF_ProjectCost(1,i)};  
 
    CashFlowSheet_TableArray(21,(i+2))={CF_RevSaleNet(1,i)};  

    CashFlowSheet_TableArray(22,(i+2))={CF_OpEx(1,i)};  

    CashFlowSheet_TableArray(23,(i+2))={CF_PrjCashFlow(1,i)};
    
    CashFlowSheet_TableArray(24,(i+2))={CF_PrjIRR(1,i)};
 
    CashFlowSheet_TableArray(25,(i+2))={CF_PrjNPV(1,i)};

    CashFlowSheet_TableArray(27,(i+2))={CF_EquInvest(1,i)};
      
    CashFlowSheet_TableArray(28,(i+2))={CF_RevSaleNet(1,i)};  

    CashFlowSheet_TableArray(29,(i+2))={CF_OpEx(1,i)};    
    
    CashFlowSheet_TableArray(30,(i+2))={CF_NetIntAmt(1,i)};

    CashFlowSheet_TableArray(31,(i+2))={CF_AppTax(1,i)};
    
    CashFlowSheet_TableArray(32,(i+2))={CF_AnPrinAmt(1,i)}; 
    
    CashFlowSheet_TableArray(33,(i+2))={CF_PrinCashFlow(1,i)};

    CashFlowSheet_TableArray(34,(i+2))={CF_EquityIRR(1,i)};  
    
    CashFlowSheet_TableArray(35,(i+2))={CF_EquityNPV(1,i)};
    
    CashFlowSheet_TableArray(37,(i+2))={CF_NetOpIncome(1,i)};
 
    CashFlowSheet_TableArray(38,(i+2))={CF_DebtService(1,i)};

    CashFlowSheet_TableArray(39,(i+2))={CF_DebtRatio(1,i)}; 
    
    CashFlowSheet_TableArray(40,(i+2))={CF_AvgDebtRatio(1,i)};    
    
 end 

%% Cell Array for Report GUI Table 

FinancialReportSheet_TableArray=cell(145,(2+(ProjectLife+1)));

% Filling Inputs Sheet

FinancialReportSheet_TableArray(1:41,1:4)=InputsSheet_TableArray;

% Filling Revenue Sheet

FinancialReportSheet_TableArray(44:52,:)=RevenueSheet_TableArray;

% Filling Debt Servicing Sheet

FinancialReportSheet_TableArray(55:70,:)=DebtServicingSheet_TableArray;

% Filling Depreciation Sheet

FinancialReportSheet_TableArray(73:84,:)=DepreciationSheet_TableArray;

% Filling Operational Expenditure Sheet

FinancialReportSheet_TableArray(87:92,:)=OperationalExpenditureSheet_TableArray;

% Filling Working Capital Sheet

FinancialReportSheet_TableArray(95:103,:)=WorkingCapitalSheet_TableArray;

% Filling Cash Flow Sheet

FinancialReportSheet_TableArray(106:145,:)=CashFlowSheet_TableArray;
