# -*- coding: utf-8 -*-
"""UnitTest_Skandha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uITA7NmpJ7pR47YpKkNNFIPyKd9oJdtr
"""

import unittest
import SolarApp_Skandha
import numpy as np


class Test_SolarApp_Skandha(unittest.TestCase):
  
  def test_GHI_PvPlantPerformance(self):
    values = np.array([10, 5, 1, 2, 3, 3 , 8 , 5 , 1 , 8 , 4 , 2])
    items = ["EArrayMod","EPgridMod","EArray","EPgrid","TotPlaneInso","ModuleTemperature","DayNum","EnergyConverter","ModTemCF","PlantCapacity","Pmod","ModNum"]
    ghi_PvPlantPerformance_Input = {key:value for key, value in zip(items, values)}
    ghi_PvPlantPerformance_Output = SolarApp_Skandha.GHI_PvPlantPerformance(
        ghi_PvPlantPerformance_Input)
    self.assertEqual(np.shape(ghi_PvPlantPerformance_Output)[0], 2)

  def test_GHI_RainSnowMonthDays(self):
    values = np.array([5, 1])
    items = ["RainSnowMonths","LeapYear"]
    ghi_RainSnowMonthDays_Input = {key:value for key, value in zip(items, values)}
    ghi_RainSnowMonthDays_Output = SolarApp_Skandha.GHI_RainSnowMonthDays(
        ghi_RainSnowMonthDays_Input)
    self.assertEqual(np.shape(ghi_RainSnowMonthDays_Output)[0], 2)

  def test_GHI_ResFileIndex(self):
    values = np.array([10, 5, 1])
    items = ["DayCounter","T","Res"]
    ghi_ResFileIndex_Input = {key:value for key, value in zip(items, 
                                                                   values)}
    ghi_ResFileIndex_Output = SolarApp_Skandha.GHI_ResFileIndex(
        ghi_ResFileIndex_Input)
    self.assertEqual(np.shape(ghi_ResFileIndex_Output)[0], 1)

  def test_SeasonalTilt(self):
    values = np.array([3, 4 , 6 , 7, 3, 9 , 5 , 8, 2 , 1, 1 , 8])
    items = ["n","L","Ib","Id","C","beta","phi","tilt","tiltsummer","tiltwinter","phic","rho"]
    SeasonalTilt_Input = {key:value for key, value in zip(items, values)}
    SeasonalTilt_Output = SolarApp_Skandha.SeasonalTilt(SeasonalTilt_Input)
    self.assertEqual(np.shape(SeasonalTilt_Output)[0], 5)

  def test_StartEndCalender(self):
    values = np.array([10, 5])
    items = ["StartYear","StartMonth","StartDay","TotDays","Res","DataCols"]
    StartEndCalender_Input = {key:value for key, value in zip(items, values)}
    StartEndCalender_Output = SolarApp_Skandha.HourlyFileIndex(
        StartEndCalender_Input)
    self.assertEqual(np.shape(StartEndCalender_Output), 3)

